
experiment_name:
  ann_snn_cnn_poisson

pytorch_seed:
  2

hyperparameters:
  # default parameters
  length:
    25
  batch_size:
    32
  synapse_type:
    'dual_exp'
  epoch:
    2
  droupout:
    0.3
  tau_m:
    4
  tau_s:
    1
  filter_tau_m:
    4
  filter_tau_s:
    1
  train_coefficients:
    True
  train_bias:
    True
  membrane_filter:
    False

optimizer:
  optimizer_choice:
    'Adam'
  Adam:
    lr: 0.0001
  AdamW:
    lr: 0.0001
  SGD:
    lr: 0.0001

scheduler:
  scheduler_choice:
    'MultiStepLR'
  MultiStepLR:
    milestones:
      - 75
      - 112
    gamma:
      0.1
  CosineAnnealingWarmRestarts:
    T_0:
      1000
  CyclicLR:
    base_lr:
      0.0001
    max_lr:
      0.001
    step_size_up:
      2000

transform:
  RandomResizedCrop:
    size:
      32
    scale:
      - 0.85
      - 1.0
    ratio:
      - 0.75
      - 1.3333333333333333
    interpolation:
      2
  RandomRotation:
    angle:
      15
  RandomApply:
    probability:
      0.5

dataset_config:
  name:
    'CIFAR10'
  in_channels:
    3
  max_rate:
    1
  use_transform:
    True
  n_class:
    10
  size_h:
    32
  size_w:
    32

# configs for saving checkpoint
save_checkpoint:
  True
checkpoint_base_name:
  checkpoint_
checkpoint_base_path:
  /checkpoint/

# the checkpoint used for test
test_checkpoint_path:
  /checkpoint/ann_snn_cnn_poisson_1

pretrained_ann_path:
  /checkpoint/best_ann_snn_cnn_poisson_1

acc_file_name:
  'ann_snn_cnn_poisson-accuracy.csv'

